//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<CarsToDriver> CarsToDrivers { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<DrivePackage> DrivePackages { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<DriverToCompany> DriverToCompanies { get; set; }
        public virtual DbSet<Ride> Rides { get; set; }
        public virtual DbSet<Role_DayRestriction> Role_DayRestriction { get; set; }
        public virtual DbSet<Role_EngineTempLimit> Role_EngineTempLimit { get; set; }
        public virtual DbSet<Role_Punished> Role_Punished { get; set; }
        public virtual DbSet<Role_RidesWithOutData> Role_RidesWithOutData { get; set; }
        public virtual DbSet<Role_RPMLimit> Role_RPMLimit { get; set; }
        public virtual DbSet<Role_SpeedLimit> Role_SpeedLimit { get; set; }
        public virtual DbSet<Role_TimeRestriction> Role_TimeRestriction { get; set; }
        public virtual DbSet<UserNotification> UserNotifications { get; set; }
        public virtual DbSet<CarsToDriverView> CarsToDriverViews { get; set; }
        public virtual DbSet<EndedRide> EndedRides { get; set; }
        public virtual DbSet<FinishRide> FinishRides { get; set; }
        public virtual DbSet<RideInfo> RideInfoes { get; set; }
    }
}
