//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarManagerDbEntities : DbContext
    {
        public CarManagerDbEntities()
            : base("name=CarManagerDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Car> Cars { get; set; }
        public DbSet<CarsToDriver> CarsToDrivers { get; set; }
        public DbSet<Company> Companies { get; set; }
        public DbSet<DrivePackage> DrivePackages { get; set; }
        public DbSet<Driver> Drivers { get; set; }
        public DbSet<DriverToCompany> DriverToCompanies { get; set; }
        public DbSet<Ride> Rides { get; set; }
        public DbSet<Role_DayRestriction> Role_DayRestriction { get; set; }
        public DbSet<Role_EngineTempLimit> Role_EngineTempLimit { get; set; }
        public DbSet<Role_Punished> Role_Punished { get; set; }
        public DbSet<Role_RidesWithOutData> Role_RidesWithOutData { get; set; }
        public DbSet<Role_RPMLimit> Role_RPMLimit { get; set; }
        public DbSet<Role_SpeedLimit> Role_SpeedLimit { get; set; }
        public DbSet<Role_TimeRestriction> Role_TimeRestriction { get; set; }
        public DbSet<CarsToDriverView> CarsToDriverViews { get; set; }
        public DbSet<EndedRide> EndedRides { get; set; }
        public DbSet<FinishRide> FinishRides { get; set; }
        public DbSet<RideInfo> RideInfoes { get; set; }
    }
}
