//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarsToDriver
    {
        public System.Guid CarId { get; set; }
        public System.Guid DriverId { get; set; }
        public System.Guid Id { get; set; }
        public Nullable<bool> offlineRideAllowed { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Role_DayRestriction Role_DayRestriction { get; set; }
        public virtual Role_EngineTempLimit Role_EngineTempLimit { get; set; }
        public virtual Role_Punished Role_Punished { get; set; }
        public virtual Role_RidesWithOutData Role_RidesWithOutData { get; set; }
        public virtual Role_RPMLimit Role_RPMLimit { get; set; }
        public virtual Role_SpeedLimit Role_SpeedLimit { get; set; }
    }
}
