//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarsToDriverView
    {
        public System.Guid Id { get; set; }
        public System.Guid CarId { get; set; }
        public System.Guid DriverId { get; set; }
        public long CarLicenseNumber { get; set; }
        public string CarModel { get; set; }
        public string DriverName { get; set; }
        public string DriverFamilyName { get; set; }
        public string DriverLicenseNumber { get; set; }
        public Nullable<bool> OfflineRideAllowed { get; set; }
    }
}
