//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Cars = new HashSet<Car>();
            this.DriverToCompanies = new HashSet<DriverToCompany>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Phone_number { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Car> Cars { get; set; }
        public virtual ICollection<DriverToCompany> DriverToCompanies { get; set; }
    }
}
