//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverToCompany
    {
        public System.Guid DriverId { get; set; }
        public System.Guid CompanyId { get; set; }
        public bool Approved { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Driver Driver { get; set; }
    }
}
