//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrivePackage
    {
        public System.Guid RideId { get; set; }
        public System.DateTime Time { get; set; }
        public Nullable<int> Speed { get; set; }
        public Nullable<int> RPM { get; set; }
        public Nullable<int> EngineTemp { get; set; }
    
        public virtual Ride Ride { get; set; }
    }
}
