//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public Driver()
        {
            this.CarsToDrivers = new HashSet<CarsToDriver>();
            this.DriverToCompanies = new HashSet<DriverToCompany>();
            this.Rides = new HashSet<Ride>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string FamilyName { get; set; }
        public string Licence { get; set; }
        public Nullable<short> ExperienceYears { get; set; }
        public int UserId { get; set; }
    
        public virtual ICollection<CarsToDriver> CarsToDrivers { get; set; }
        public virtual ICollection<DriverToCompany> DriverToCompanies { get; set; }
        public virtual ICollection<Ride> Rides { get; set; }
    }
}
