//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_Punished
    {
        public System.Guid DriverId { get; set; }
        public System.DateTime expirationDate { get; set; }
    
        public virtual CarsToDriver CarsToDriver { get; set; }
    }
}
