//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_SpeedLimit
    {
        public System.Guid CarToDriverId { get; set; }
        public Nullable<short> WarningLimit { get; set; }
        public Nullable<short> CountBrokeWarningLimit { get; set; }
        public Nullable<short> MaxtBrokeWarningLimit { get; set; }
        public Nullable<short> PunishmentLimit { get; set; }
        public Nullable<short> CountBrokePunishmentLimit { get; set; }
        public Nullable<short> MaxtBrokePunishmentLimit { get; set; }
    
        public virtual CarsToDriver CarsToDriver { get; set; }
    }
}
