//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotification
    {
        public int UserId { get; set; }
        public string Topic { get; set; }
        public string Message { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
