//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarManagerWebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarManagerDbEntities2 : DbContext
    {
        public CarManagerDbEntities2()
            : base("name=CarManagerDbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<DrivePackage> DrivePackage { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<Ride> Ride { get; set; }
        public virtual DbSet<Role_DayRestriction> Role_DayRestriction { get; set; }
        public virtual DbSet<Role_TimeRestriction> Role_TimeRestriction { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<EndedRides> EndedRides { get; set; }
        public virtual DbSet<FinishRide> FinishRide { get; set; }
        public virtual DbSet<RideInfo> RideInfo { get; set; }
    }
}
